### ISSUE TITLE
Current IRC links to Freenode need to be replaced with links to Libera.Chat

### ISSUE THREAD

**Issue by jamestmartin** [proglangdesign/proglangdesign.github.io#132]
Hi! I'm sure you're all already aware of the Freenode drama. Please reply to this issue with the channel your project is currently using. I'll replace your IRC channel links in a few days when I get a chance to add Libera.Chat to the website. If you migrated to a network other than Libera.Chat, I will add that as well.

@mertyildiran
@ErmineII
@technomancy 
@evincarofautumn 
@MostAwesomeDude

As an aside, the riot.im link on the website needs to be updated to use Libera.Chat if any of you happen to use Riot and know the channel name.

**Comment by athas** [comment]
The IRC reference already mentions Libera Chat, but I think the riot.im bridge did not exist yet when that was updated.  I don't know anything about riot.im, so I don't know what it should be now.

**Comment by technomancy** [comment]
Thanks; Fennel has moved to `#fennel` on Libera and is also available on `#fennel:matrix.org` bridged to the same channel.

Also our git repository has moved to Sourcehut: https://git.sr.ht/~technomancy/fennel and now the repo on github is a read-only mirror.

**Comment by athas** [comment]
PRs welcome.

**Comment by mertyildiran** [comment]
@jamestmartin `#chaoslang` on Libera.
