### ISSUE TITLE
Monolithic programming language

### ISSUE THREAD

**Issue by CitoplasmaX** [proglangdesign/proglangdesign.github.io#14]
I know there's no story here, but I do not know what taxpayers know about a programming language that specializes in monolithic programming. With monolithic programming, in case someone does not know, I want to refer to the paradigm that does not have an article in wikipedia or is basically badly redirected (to monolithic application) and that is to create programs following the standard of structured programming but instead of possibility to create several functions or procedures, the program consists of a single main function.

Well said that. I wanted to look for some language of that kind, I know that some Algol dialects are like this but it's difficult for the syntax to work today with modern compilers and so I prefer to ask for one that someone has done recently or is doing to learn, quite.

Finally, it would be preferable if it were a compiled language, clearly.

**Comment by Athas** [comment]
I think you took a wrong turn somewhere - this is a Github repository for documenting the projects of a bunch of language nerds on IRC.  You may want to ask such questions on [/r/programminglanguages](http://programminglanguages.reddit.com/) instead.

**Comment by CitoplasmaX** [comment]
Thanks
