### ISSUE TITLE
There should be a way to specify source locations not on github.com or gitlab.com

### ISSUE THREAD

**Issue by ell1e** [proglangdesign/proglangdesign.github.io#179]
My project doesn't live on GitHub.com or Gitlab.com (there's a mirror on GitHub but I don't want to link people to the mirror unnecessarily) but on a different git host, and in the age of possibly self-hosted Gitea/GitLab/.../whatever instances and in the spirit of open-source and friendly competition and diversity, I think it should be encouraged to specify whatever other platform for code. Maybe a generic `repo` or `source` or `git` key could allow any `https://...` link like the website, and would then show the git icon? I guess allowing something else than git would be even nicer, but I can't of what the icon should be in that case, and I guess nobody really practically uses something else than git for programming language projects these days anyway.

**Comment by athas** [comment]
In the old days where this was a straightforward HTML page, this would be trivial.  Today, in the age of automation and YAML, I have no idea how to do this.
