### ISSUE TITLE
Remove www. from the domain

### ISSUE THREAD

**Issue by jamestmartin** [proglangdesign/proglangdesign.github.io#42]
I don't like the `www.`, and tried to remove it as part of the redesign, since the site is always advertised as `proglangdesign.net` anyway. However, trying to connect without the `www.` results in issues with HTTPS (the certificate is *only* issued for the `www.`, not the base domain, even though the DNS at the very least redirects to the correct site). Even with updating the `CNAME` file, that did not fix the issue.

It remains to be seen how this can be fixed.

**Comment by jamestmartin** [comment]
Regarding HTTPS, see also #25. Some-one unchecked the `Enforce HTTPS` box without discussing it first.

**Comment by jamestmartin** [comment]
Oops. Didn't mean to close this.

**Comment by jamestmartin** [comment]
I did now, yes.

**Comment by SafelySwift** [comment]
Does it work?

**Comment by jamestmartin** [comment]
It does work in that you are now restricted to using HTTPS so you won't accidentally be redirected to `http://proglangdesign.net`. However, it doesn't change that the Let's Encrypt certificate issued for this site only includes the `www.` domain, and not the base domain.

**Comment by jamestmartin** [comment]
Ideally I'd still like this, but I don't think anyone cares enough to pursue it in practice.

**Comment by jamestmartin** [comment]
I ended up pursuing it in practice, and it's now been fixed. The issue was that the `A` records for the apex domain were wrong, and now that @ chrisosaurus  has fixed them, the site works with https without www!
