### ISSUE TITLE
Blinker not working on first load

### ISSUE THREAD

**Issue by SafelySwift** [proglangdesign/proglangdesign.github.io#53]
I have to load the webpage multiple times for the underscore to blink. I am wondering why this is...

**Comment by jamestmartin** [comment]
Is this still a problem? Has anyone else been able to reproduce this?

**Comment by SafelySwift** [comment]
Yes it is still a problem

**Comment by pawwkm** [comment]
I can't reproduce it using Chrome on Windows 10.

**Comment by jamestmartin** [comment]
I can't reproduce it with 64-bit Firefox 65.0.1on Linux. What browser are you using?

**Comment by slavfox** [comment]
Can't reproduce on Firefox 65.0.2-1 Linux ~~(arch btw)~~ either

**Comment by SafelySwift** [comment]
I can't reproduce the problem anymore on Safari High Sierra - after update to Safari.
