### ISSUE TITLE
Chika's logo isn't displaying on the website

### ISSUE THREAD

**Issue by phunanon** [proglangdesign/proglangdesign.github.io#83]
I think it might be because it's such an aggressively compressed SVG, but it is valid. Should I reupload with a more compliant SVG, or is this a website issue?

**Comment by jamestmartin** [comment]
You forgot to include `icon: chika.svg` in `projects.yml`. I fixed it: https://github.com/proglangdesign/proglangdesign.github.io/commit/1f4668d1d38f9108e924ebafa11736e9bc6250f9
