### ISSUE TITLE
External logo URLs

### ISSUE THREAD

**Issue by ell1e** [proglangdesign/proglangdesign.github.io#89]
It appears that linking logo URLs externally doesn't appear to work. Since I have no idea of how to install & run ruby website things, I can't test it locally but with the liquid templating reference I believe something like this could work **(untested)**:

```
{% if project.icon and project.icon contains "://" %}
<img src="{{ project.icon }}" alt="" />
{% else %}
<img src="/images/lang/{{ project.icon | default: 'placeholder.png' }}" alt="" />
{% endif %}
```

Anyone who can actually test it feel free to try this out and make a pull request. You should be able to see with the Horse64 logo if the external URL works out fine or not.

**Comment by athas** [comment]
Nobody ~~can~~ wants to run all that Ruby stuff.  The brave and true test in production anyway!

**Comment by jamestmartin** [comment]
Your fixed worked and is now live.
